env: "${ENV}"
shows:
  - title: "One Room, Hiatari Futsuu, Tenshi-tsuki"
    source: "Crunchyroll"
  - title: "Mushoku Tensei S2"
    source: "Crunchyroll"
  - title: "Sasayaku You ni Koi wo Utau"
    source: "Subsplease"
  - title: "Seiyuu Radio no Uraomote"
    source: "Crunchyroll"
  - title: "Yoru no Kurage wa Oyogenai"
    source: "Subsplease"
  - title: "Kaijuu 8-gou"
    source: "Crunchyroll"
  - title: "Spice and Wolf (2024)"
    source: "Crunchyroll"
  - title: "Shuumatsu Train Doko e Iku"
    source: "Crunchyroll"
manualShows:
  - name: "An Archdemons Dilemma: How to Love Your Elf Bride"
    day: "Thursday"
    time: "17:00"
    source: "Crunchyroll"
  - name: "Yozakura-san Chi no Daisakusen"
    day: "Monday"
    time: "09:00"
    source: "Nyaa"
subsPlease:
  baseUrl: "https://subsplease.org/api/?f=schedule&h=true"
  timeZone: "europe/london"
telegram:
  token: "${TG_API_TOKEN}"
  chatId: "${TG_CHAT_ID}"
