env: '${ENV}'
shows:
  - 'Zom 100 - Zombie ni Naru made ni Shitai 100 no Koto'
  - 'Rurouni Kenshin (2023)'
  - 'Uchi no Kaisha no Chiisai Senpai no Hanashi'
  - 'Mushoku Tensei S2'
manualShows:
  # - name: 'Tengoku Daimakyou'
  #   day: 'Saturday'
  #   time: '14:00'
subsPlease:
  baseUrl: 'https://subsplease.org/api/?f=schedule&h=true'
  timeZone: 'europe/london'
telegram:
  token: '${TG_API_TOKEN}'
  chatId: '${TG_CHAT_ID}'
