env: "${ENV}"
shows:
  - title: "Haite Kudasai, Takamine-san"
    source: "SubsPlease"
  - title: "Kowloon Generic Romance"
    source: "Crunchyroll"
  - title: "Kakushite! Makina-san!!"
    source: "SubsPlease"
  - title: "Kidou Senshi Gundam: GQuuuuuuX"
    source: "Crunchyroll"
  - title: "Aharen-san wa Hakarenai Season 2"
    source: "Crunchyroll"
manualShows:
  - title: "Kakushite Makina-san"
    day: "Sunday"
    source: "Nyaa"
    time: "17:30"
  - title: "Lazarus"
    day: "Sunday"
    source: "Nyaa"
    time: "17:30"
subsPlease:
  baseUrl: "https://subsplease.org/api/?f=schedule&h=true"
  timeZone: "europe/london"
telegram:
  token: "${TG_API_TOKEN}"
  chatId: "${TG_CHAT_ID}"
