env: '${ENV}'
shows:
  - Chainsaw Man
  - Spy x Family
  - Uzaki-chan wa Asobitai! S2
  - Do It Yourself!!
  - Renai Flops
  - Berserk - The Golden Age Arc Memorial Edition
  - Mobile Suit Gundam - The Witch from Mercury
  - Arknights - Reimei Zensou
manualShows:
  - name: 'Futoku no Guild'
    day: 'Wednesday'
    time: '18:00'
subsPlease:
  baseUrl: 'https://subsplease.org/api/?f=schedule&h=true'
  timeZone: europe/london
telegram:
  token: '${TG_API_TOKEN}'
  chatId: '${TG_CHAT_ID}'
